# ==========================================
# NEON.TECH CLOUD DATABASE CONFIGURATION
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-flat-grass-a1gb39gp-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8zVl6QcoPfsw

# ==========================================
# HIBERNATE & JPA SETTINGS
# ==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# ==========================================
# JWT SECURITY
# ==========================================
jwt.secret=your_super_secret_key_change_this_in_production_to_something_very_long